name: exam_app_itasoft
description: "Test Section 5"

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1


dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  flutter_easyloading: ^3.0.5
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.2.8
  freezed_annotation:
  infinite_scroll_pagination: ^4.0.0
  dropdown_search: ^5.0.3
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  freezed:
  json_serializable:
  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

